version: "3"

services:
  backend:
    build: ./backend
    image: "cards-offending-mankind/backend:dev"
    depends
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: always
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always