# DEV environment

version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: 'cards-offending-mankind/frontend:dev'
    ports:
      - 80:8080
    environment:
      NODE_ENV: development
      BASE_URL: http://localhost/
    volumes:
      - ./frontend:/opt/app
      - ./types:/opt/types
      - /opt/app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: 'cards-offending-mankind/backend:dev'
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
    volumes:
      - ./backend:/opt/app
      - ./types:/opt/types
      - /opt/app/node_modules
    depends_on:
      - redis

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - /data
