# base image
FROM node:16-alpine

# set working directory
WORKDIR /opt/app

ENV PATH /opt/app/node_modules/.bin:$PATH

COPY entrypoint-dev.sh .
ENTRYPOINT ["sh", "./entrypoint-dev.sh"]

# Link to /opt/app injected by compose file

EXPOSE 3000

# start app
CMD ["yarn", "dev"]
