openapi: 3.0.1
info:
  title: backend
  description: Cards-Offending-Mankind Backend
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: Specification
    description: The swagger API specification
  - name: Packs
    description: Card Packs
  - name: Games
    description: Games
paths:
  /packs:
    get:
      summary: Get Packs
      tags:
        - Packs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  description: Pack
                  properties:
                    abbr:
                      type: string
                    name:
                      type: string
                    icon:
                      type: string
                    description:
                      type: string
                    official:
                      type: boolean
              examples: {}
          headers: {}
      operationId: get-packs
      description: Returns a list of all packs
  /spec:
    get:
      tags:
        - Specification
      responses:
        '200':
          description: Return the API specification
          content: {}
      operationId: get-openapi-spec
      description: ''
  /games:
    post:
      summary: Create Game
      operationId: post-games
      responses:
        '200':
          description: OK
      description: 'Creates '
      tags:
        - Games
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
components:
  schemas: {}
