openapi: 3.0.1
info:
  title: backend
  description: Cards-Offending-Mankind Backend
  version: 1.0.0
  license:
    name: MIT
  contact:
    url: 'https://www.mankind.cards/legal'
servers:
  - url: /api/v1
tags:
  - name: Specification
    description: The swagger API specification
  - name: Packs
    description: Card Packs
  - name: Games
    description: Games
paths:
  /packs:
    get:
      summary: Get Packs
      tags:
        - Packs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PackInformation'
              examples: {}
          headers: {}
      operationId: get-packs
      description: Returns a list of all packs
  /spec:
    get:
      tags:
        - Specification
      responses:
        '200':
          description: Return the API specification
          content: {}
      operationId: get-openapi-spec
      description: Return OpenAPI Spec.
      summary: OpenAPI specification
  /games:
    post:
      summary: Create Game
      operationId: post-games
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  game:
                    $ref: '#/components/schemas/Game'
                  player:
                    $ref: '#/components/schemas/Player'
                required:
                  - game
                  - player
        '400':
          $ref: '#/components/responses/Error'
      description: Creates a new Game.
      tags:
        - Games
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                game:
                  $ref: '#/components/schemas/CreateGame'
                player:
                  type: object
                  required:
                    - nickname
                  properties:
                    nickname:
                      type: string
                      minLength: 3
              required:
                - game
                - player
  '/games/{GameID}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: GameID
        in: path
        required: true
    get:
      summary: Retrieve Game Information
      tags:
        - Games
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  game:
                    $ref: '#/components/schemas/Game'
                required:
                  - game
              examples: {}
        '400':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
      operationId: get-games-gameId
      description: Get a Game by it's ID.
  '/games/{GameID}/join':
    parameters:
      - schema:
          type: string
          format: uuid
        name: GameID
        in: path
        required: true
    post:
      summary: Join Game
      operationId: post-games-gameId-join
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  player:
                    $ref: '#/components/schemas/Player'
                required:
                  - player
        '400':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
      tags:
        - Games
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nickname:
                  type: string
                  minLength: 3
                password:
                  type: string
              required:
                - nickname
        description: ''
      description: Create a new Player for a Game.
components:
  schemas:
    Player:
      title: FullPlayer
      type: object
      properties:
        id:
          type: string
        nickname:
          type: string
        points:
          type: integer
        isAI:
          type: boolean
        isActive:
          type: boolean
        isHost:
          type: boolean
        deck:
          type: array
          items:
            type: object
        token:
          type: string
      required:
        - id
        - nickname
        - points
        - isAI
        - isActive
        - isHost
        - deck
        - token
    Pack:
      title: Pack
      type: object
      properties:
        abbr:
          type: string
        name:
          type: string
        isOfficial:
          type: boolean
      required:
        - abbr
    Game:
      title: Game
      type: object
      properties:
        hasPassword:
          type: boolean
        status:
          type: string
          default: created
          enum:
            - created
            - running
            - ended
        packs:
          type: array
          items:
            $ref: '#/components/schemas/Pack'
        id:
          type: string
          format: uuid
        winnerPoints:
          oneOf:
            - type: boolean
              enum:
                - false
            - type: integer
              default: 20
              minimum: 1
        timeouts:
          type: object
          properties:
            playing:
              type: integer
              default: 120
              minimum: 5
            revealing:
              type: integer
              default: 60
              minimum: 5
            judging:
              type: integer
              default: 120
              minimum: 5
            betweenRounds:
              type: integer
              default: 30
              minimum: 5
        handSize:
          type: integer
          minimum: 2
        specialRules:
          type: object
          properties:
            aiPlayerCount:
              type: integer
              default: 0
              minimum: 0
              maximum: 3
            allowDiscarding:
              type: object
              properties:
                enabled:
                  type: boolean
                  default: false
                penalty:
                  type: integer
                  default: 0
                  minimum: 0
                  maximum: 5
            pickExtra:
              type: boolean
              default: false
    CreateGame:
      title: Game
      type: object
      properties:
        timeouts:
          type: object
          properties:
            playing:
              type: integer
              default: 120
              minimum: 5
            revealing:
              type: integer
              default: 60
              minimum: 5
            judging:
              type: integer
              default: 120
              minimum: 5
            betweenRounds:
              type: integer
              default: 30
              minimum: 5
        winnerPoints:
          oneOf:
            - type: boolean
              enum:
                - false
            - type: integer
              default: 20
              minimum: 1
        handSize:
          type: integer
          default: 10
          minimum: 2
        password:
          type: string
        packs:
          type: array
          items:
            $ref: '#/components/schemas/Pack'
        specialRules:
          type: object
          properties:
            aiPlayerCount:
              type: integer
              default: 0
              minimum: 0
              maximum: 3
            allowDiscarding:
              type: object
              properties:
                enabled:
                  type: boolean
                  default: false
                penalty:
                  type: integer
                  default: 0
                  minimum: 0
                  maximum: 5
            pickExtra:
              type: boolean
              default: false
    PackInformation:
      title: PackInformation
      allOf:
        - $ref: '#/components/schemas/Pack'
        - type: object
          properties:
            promptsCount:
              type: integer
            responsesCount:
              type: integer
  responses:
    Error:
      description: Error response.
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              errorCode:
                type: string
                nullable: true
              errors:
                type: array
                uniqueItems: true
                minItems: 1
                items:
                  type: object
                  properties:
                    errorCode:
                      type: string
                    message:
                      type: string
                      minLength: 1
                    path:
                      type: string
                  required:
                    - message
            required:
              - errors
